# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8RQm9XT7hx1vqJxt6SzpedeX0UmyWhV
"""

from sympy import *
t,s,a,b = symbols('t,s,a,b')
y = exp(2*t)*sin(2*t)
Y = laplace_transform(y,t,s)
display(simplify(Y))

y = sinh(2*t)
Y = laplace_transform(y,t,s)
display(simplify(Y))

# prompt: laplace transform of sint from 0 to pi/2

from sympy import *
t,s,a,b = symbols('t,s,a,b')
y = sin(t)
Y = laplace_transform(y,t,s, noconds=True)
display(simplify(Y))
lower_limit = 0
upper_limit = pi/2
result = integrate(y * exp(-s*t), (t, lower_limit, upper_limit))
display(result)

x = symbols('x')
f = (pi-x)/2
FS = fourier_series(f,(x,-pi,pi))
display(FS)
FS1 = FS.truncate(n=5)
display(FS1)
plot(FS1)

f = sqrt(1-cos(x))
FS = fourier_series(f,(x,-pi,pi))
display(FS)
FS1 = FS.truncate(n=5)
display(FS1)
plot(FS1)